# Generated by Django 4.0.3 on 2023-02-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(choices=[('SMTL', 'Самотлорнефтегаз'), ('SKNG', 'Севкомнефтегаз'), ('UVAT', 'Уватнефтегаз'), ('SBNG', 'Сибнефтегаз'), ('UDMR', 'Удмуртнефть'), ('TUNG', 'ТЮНГ'), ('UGNG', 'Юганскнефтегаз')], max_length=4, verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd_contractor_name', models.CharField(max_length=100, verbose_name='Подрядчик по ННБ')),
                ('drill_contractor_name', models.CharField(max_length=100, verbose_name='Подрядчик по бурению')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Месторождение')),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Field.client', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pad_name', models.CharField(max_length=20, verbose_name='Куст')),
                ('field_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pads', to='Field.field', verbose_name='Месторождение')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_name', models.CharField(max_length=20, verbose_name='Скважина')),
                ('active_from', models.FloatField(verbose_name='Активная фаза')),
                ('status', models.CharField(choices=[('PLAN', 'Планируется'), ('NOTA', 'Активная фаза с <django.db.models.fields.FloatField> м'), ('ACTV', 'В активной фазе'), ('FINI', 'Добурена')], max_length=4, verbose_name='Статус')),
                ('in_statistics', models.BooleanField(verbose_name='учитывать в статистике')),
                ('well_type', models.CharField(choices=[('VNS0', 'ВНС'), ('NNS0', 'ННС'), ('ZBS0', 'ЗБС'), ('BGS0', 'БГС')], max_length=4, verbose_name='Тип скважины')),
                ('RKB', models.FloatField(verbose_name='Альтитуда стола ротора')),
                ('coordinate_system', models.CharField(max_length=20, verbose_name='Система координат')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longtitude', models.FloatField(verbose_name='Долгота')),
                ('NY', models.FloatField(verbose_name='Широта (прямоугольные координаты)')),
                ('EX', models.FloatField(verbose_name='Долгота (прямоугольные координаты)')),
                ('north_direction', models.CharField(choices=[('GRID', 'Картографический'), ('TRUE', 'Истинный'), ('MAGN', 'Магнитный')], max_length=4, verbose_name='Направление на север')),
                ('geomagnetic_model', models.CharField(max_length=20, verbose_name='Геомагнитная модель')),
                ('geomagnetic_date', models.DateField(verbose_name='Дата геомагнитной привязки')),
                ('btotal', models.FloatField(verbose_name='Напряженность геомагнитного поля')),
                ('dip', models.FloatField(verbose_name='Магнитное наклонение')),
                ('dec', models.FloatField(verbose_name='Магнитное склонение')),
                ('dip_convergence', models.FloatField(verbose_name='Сближение меридианов')),
                ('total_correction', models.FloatField(verbose_name='Общая поправка')),
                ('gtotal', models.FloatField(verbose_name='Напряженность гравитационного поля')),
                ('T1_start', models.DateField(verbose_name='Начало сопровождения до Т1')),
                ('T1_end', models.DateField(verbose_name='Начало сопровождения до Т3')),
                ('T3_start', models.DateField(verbose_name='Окончание сопровождения до Т1')),
                ('T3_end', models.DateField(verbose_name='Окончание сопровождения до Т3')),
                ('critical_azimuth', models.BooleanField(verbose_name='Критический азимут')),
                ('comment', models.TextField(max_length=300, verbose_name='Комментарий')),
                ('pad_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='Field.pad', verbose_name='Куст')),
            ],
        ),
        migrations.CreateModel(
            name='Wellbore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellbore', models.CharField(choices=[('PLT0', 'ПЛ'), ('PLT1', 'ПЛ1'), ('PLT2', 'ПЛ2'), ('MAIN', 'ОС'), ('BGS0', 'БГС'), ('ST01', 'СТ1'), ('ST02', 'СТ2'), ('ST03', 'СТ3'), ('ST04', 'СТ4'), ('BS01', 'БС1'), ('BS02', 'БС2'), ('BS03', 'БС3'), ('BS04', 'БС4'), ('BS05', 'БС5'), ('BS06', 'БС6'), ('BS07', 'БС7'), ('BS08', 'БС8')], max_length=4, verbose_name='Ствол')),
                ('well_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wellbores', to='Field.well', verbose_name='Скважина')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20, verbose_name='Секция')),
                ('target_depth', models.FloatField(verbose_name='Плановая глубина')),
                ('wellbore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Field.wellbore', verbose_name='Ствол')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField(verbose_name='Рейс')),
                ('start_date', models.DateField(verbose_name='Дата начала рейса')),
                ('end_date', models.DateField(verbose_name='Дата окончания рейса')),
                ('start_depth', models.FloatField(verbose_name='Глубина начала рейса')),
                ('end_depth', models.FloatField(verbose_name='Конечная глубина рейса')),
                ('in_statistics', models.BooleanField(verbose_name='Учитывать в статистике')),
                ('memory', models.CharField(choices=[('RQT1', 'Запрошена'), ('RQT2', 'Запрошена повторно'), ('RCIV', 'Получена'), ('CHEK', 'Проверена'), ('NMEM', 'Без памяти'), ('NOTR', 'Не предоставлена')], max_length=4, verbose_name='Память')),
                ('bha', models.CharField(choices=[('RQT1', 'Запрошена'), ('RQT2', 'Запрошена повторно'), ('RCIV', 'Получена'), ('SLIK', 'Гладкая'), ('SAGC', 'SAG посчитан')], max_length=4, verbose_name='КНБК')),
                ('sag', models.FloatField(verbose_name='SAG')),
                ('dd_contractor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='Field.contractor', verbose_name='Подрядчик по ННБ')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='Field.section', verbose_name='Секция')),
            ],
        ),
    ]
