# Generated by Django 4.0.3 on 2023-02-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Дочернее общество'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Подрядчики'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Месторождение'},
        ),
        migrations.AlterModelOptions(
            name='pad',
            options={'verbose_name': 'Куст'},
        ),
        migrations.AlterModelOptions(
            name='Field',
            options={'verbose_name': 'Рейс'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция'},
        ),
        migrations.AlterModelOptions(
            name='well',
            options={'verbose_name': 'Скважина'},
        ),
        migrations.AlterModelOptions(
            name='wellbore',
            options={'verbose_name': 'Ствол'},
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='contractor',
            table='сontractor',
        ),
    ]
