# Generated by Django 4.0.3 on 2023-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0003_alter_client_options_alter_contractor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Месторождение'),
        ),
        migrations.AlterField(
            model_name='well',
            name='status',
            field=models.CharField(choices=[('PLAN', 'Планируется'), ('NOTA', 'Активная фаза'), ('ACTV', 'В активной фазе'), ('FINI', 'Добурена')], max_length=4, verbose_name='Статус'),
        ),
    ]
