# Generated by Django 4.0.3 on 2023-03-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0006_contractordrill_contractornnb_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractorNNB',
            new_name='Contractor',
        ),
    ]
