# Generated by Django 4.0.3 on 2023-03-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0007_rename_contractornnb_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='drill_contractor_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Подрядчик по бурению'),
        ),
    ]
