# Generated by Django 4.0.3 on 2023-03-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0008_contractor_drill_contractor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorNNB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd_contractor_name', models.CharField(max_length=100, verbose_name='Подрядчик по ННБ')),
            ],
            options={
                'verbose_name': 'Подрядчик по ННБ',
                'verbose_name_plural': 'Подрядчики по ННБ',
            },
        ),
        migrations.AlterField(
            model_name='run',
            name='dd_contractor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='Field.contractornnb', verbose_name='Подрядчик по ННБ'),
        ),
        migrations.DeleteModel(
            name='Contractor',
        ),
    ]
