# Generated by Django 4.0.3 on 2023-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0010_alter_field_field_name_alter_run_bha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Месторождение'),
        ),
        migrations.AlterField(
            model_name='run',
            name='bha',
            field=models.CharField(choices=[('RQT1', 'Запрошена'), ('RQT2', 'Запрошена повторно'), ('RCIV', 'Получена'), ('SLIK', 'Гладкая'), ('SAGC', 'SAG посчитан')], max_length=4, null=True, verbose_name='КНБК'),
        ),
        migrations.AlterField(
            model_name='run',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Дата окончания рейса'),
        ),
        migrations.AlterField(
            model_name='run',
            name='end_depth',
            field=models.FloatField(null=True, verbose_name='Конечная глубина рейса'),
        ),
        migrations.AlterField(
            model_name='run',
            name='in_statistics',
            field=models.BooleanField(null=True, verbose_name='Учитывать в статистике'),
        ),
        migrations.AlterField(
            model_name='run',
            name='memory',
            field=models.CharField(choices=[('RQT1', 'Запрошена'), ('RQT2', 'Запрошена повторно'), ('RCIV', 'Получена'), ('CHEK', 'Проверена'), ('NMEM', 'Без памяти'), ('NOTR', 'Не предоставлена')], max_length=4, null=True, verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='run',
            name='sag',
            field=models.FloatField(null=True, verbose_name='SAG'),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала рейса'),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_depth',
            field=models.FloatField(null=True, verbose_name='Глубина начала рейса'),
        ),
        migrations.AlterField(
            model_name='section',
            name='target_depth',
            field=models.FloatField(null=True, verbose_name='Плановая глубина'),
        ),
        migrations.AlterField(
            model_name='well',
            name='EX',
            field=models.FloatField(null=True, verbose_name='Долгота (прямоугольные координаты)'),
        ),
        migrations.AlterField(
            model_name='well',
            name='NY',
            field=models.FloatField(null=True, verbose_name='Широта (прямоугольные координаты)'),
        ),
        migrations.AlterField(
            model_name='well',
            name='RKB',
            field=models.FloatField(null=True, verbose_name='Альтитуда стола ротора'),
        ),
        migrations.AlterField(
            model_name='well',
            name='T1_end',
            field=models.DateField(null=True, verbose_name='Начало сопровождения до Т3'),
        ),
        migrations.AlterField(
            model_name='well',
            name='T1_start',
            field=models.DateField(null=True, verbose_name='Начало сопровождения до Т1'),
        ),
        migrations.AlterField(
            model_name='well',
            name='T3_end',
            field=models.DateField(null=True, verbose_name='Окончание сопровождения до Т3'),
        ),
        migrations.AlterField(
            model_name='well',
            name='T3_start',
            field=models.DateField(null=True, verbose_name='Окончание сопровождения до Т1'),
        ),
        migrations.AlterField(
            model_name='well',
            name='active_from',
            field=models.FloatField(null=True, verbose_name='Активная фаза'),
        ),
        migrations.AlterField(
            model_name='well',
            name='btotal',
            field=models.FloatField(null=True, verbose_name='Напряженность геомагнитного поля'),
        ),
        migrations.AlterField(
            model_name='well',
            name='comment',
            field=models.TextField(max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='well',
            name='coordinate_system',
            field=models.CharField(max_length=20, null=True, verbose_name='Система координат'),
        ),
        migrations.AlterField(
            model_name='well',
            name='critical_azimuth',
            field=models.BooleanField(null=True, verbose_name='Критический азимут'),
        ),
        migrations.AlterField(
            model_name='well',
            name='dec',
            field=models.FloatField(null=True, verbose_name='Магнитное склонение'),
        ),
        migrations.AlterField(
            model_name='well',
            name='dip',
            field=models.FloatField(null=True, verbose_name='Магнитное наклонение'),
        ),
        migrations.AlterField(
            model_name='well',
            name='dip_convergence',
            field=models.FloatField(null=True, verbose_name='Сближение меридианов'),
        ),
        migrations.AlterField(
            model_name='well',
            name='geomagnetic_date',
            field=models.DateField(null=True, verbose_name='Дата геомагнитной привязки'),
        ),
        migrations.AlterField(
            model_name='well',
            name='geomagnetic_model',
            field=models.CharField(max_length=20, null=True, verbose_name='Геомагнитная модель'),
        ),
        migrations.AlterField(
            model_name='well',
            name='gtotal',
            field=models.FloatField(null=True, verbose_name='Напряженность гравитационного поля'),
        ),
        migrations.AlterField(
            model_name='well',
            name='in_statistics',
            field=models.BooleanField(null=True, verbose_name='учитывать в статистике'),
        ),
        migrations.AlterField(
            model_name='well',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='well',
            name='longtitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='well',
            name='north_direction',
            field=models.CharField(choices=[('GRID', 'Картографический'), ('TRUE', 'Истинный'), ('MAGN', 'Магнитный')], max_length=4, null=True, verbose_name='Направление на север'),
        ),
        migrations.AlterField(
            model_name='well',
            name='status',
            field=models.CharField(choices=[('PLAN', 'Планируется'), ('NOTA', 'Активная фаза'), ('ACTV', 'В активной фазе'), ('FINI', 'Добурена')], max_length=4, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='well',
            name='total_correction',
            field=models.FloatField(null=True, verbose_name='Общая поправка'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_type',
            field=models.CharField(choices=[('VNS0', 'ВНС'), ('NNS0', 'ННС'), ('ZBS0', 'ЗБС'), ('BGS0', 'БГС')], max_length=4, null=True, verbose_name='Тип скважины'),
        ),
    ]
