# Generated by Django 4.0.3 on 2023-03-13 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0011_alter_field_field_name_alter_run_bha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='pad_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='Field.pad', verbose_name='Куст'),
        ),
    ]
