# Generated by Django 4.0.3 on 2023-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0012_alter_well_pad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractordrill',
            name='drill_contractor_name',
            field=models.CharField(max_length=100, verbose_name='Подрядчик по бурению'),
        ),
    ]
