# Generated by Django 4.0.3 on 2023-03-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0013_alter_contractordrill_drill_contractor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала рейса'),
        ),
    ]
