# Generated by Django 4.0.3 on 2023-03-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0014_alter_run_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала рейса'),
        ),
    ]
