# Generated by Django 4.0.3 on 2023-03-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0016_alter_run_bha_alter_run_end_date_alter_run_end_depth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='RKB',
            field=models.FloatField(blank=True, null=True, verbose_name='Альтитуда стола ротора'),
        ),
    ]
