# Generated by Django 4.0.3 on 2023-03-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0017_alter_well_rkb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='dip_convergence',
            new_name='grid_convergence',
        ),
    ]
