# Generated by Django 4.0.3 on 2023-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0018_rename_dip_convergence_well_grid_convergence'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='VSaz',
            field=models.FloatField(blank=True, null=True, verbose_name='Азимут вертикальной секции'),
        ),
    ]
