# Generated by Django 4.0.3 on 2023-04-05 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0019_well_vsaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='RKB',
            field=models.FloatField(blank=True, default=84, null=True, verbose_name='Альтитуда стола ротора'),
        ),
        migrations.AlterField(
            model_name='well',
            name='VSaz',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(360)], verbose_name='Азимут вертикальной секции'),
        ),
    ]
