# Generated by Django 4.0.3 on 2023-04-05 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0020_alter_well_rkb_alter_well_vsaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='VSaz',
            field=models.FloatField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)], verbose_name='Азимут вертикальной секции'),
        ),
    ]
