# Generated by Django 4.0.3 on 2023-04-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0021_alter_well_vsaz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='pad_name',
            new_name='pad_id',
        ),
    ]
