# Generated by Django 4.0.3 on 2023-04-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0022_rename_pad_name_well_pad_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='well',
            old_name='pad_id',
            new_name='pad_name',
        ),
    ]
