# Generated by Django 4.0.3 on 2023-04-10 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0023_rename_pad_id_well_pad_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='client_name',
            new_name='client',
        ),
    ]
