# Generated by Django 4.0.3 on 2023-04-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0024_rename_client_name_field_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pad',
            old_name='field_name',
            new_name='field',
        ),
    ]
