# Generated by Django 4.0.3 on 2023-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0025_rename_field_name_pad_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(choices=[('SMTL', 'Самотлорнефтегаз'), ('SKNG', 'Севкомнефтегаз'), ('UVAT', 'Уватнефтегаз'), ('SBNG', 'Сибнефтегаз'), ('UDMR', 'Удмуртнефть'), ('TUNG', 'ТЮНГ'), ('UGNG', 'Юганскнефтегаз')], max_length=4, unique=True, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='contractordrill',
            name='drill_contractor_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Подрядчик по бурению'),
        ),
        migrations.AlterField(
            model_name='contractornnb',
            name='dd_contractor_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Подрядчик по ННБ'),
        ),
        migrations.AlterUniqueTogether(
            name='pad',
            unique_together={('field', 'pad_name')},
        ),
    ]
