# Generated by Django 4.0.3 on 2023-04-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0026_alter_client_client_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='run',
            unique_together={('section', 'run_number')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('section', 'wellbore')},
        ),
        migrations.AlterUniqueTogether(
            name='well',
            unique_together={('well_name', 'pad_name')},
        ),
        migrations.AlterUniqueTogether(
            name='wellbore',
            unique_together={('well_name', 'wellbore')},
        ),
    ]
