# Generated by Django 4.0.3 on 2023-04-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0027_alter_run_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='active_from',
            field=models.FloatField(blank=True, null=True, verbose_name='Глубина начала активной фазы'),
        ),
    ]
