# Generated by Django 4.0.3 on 2023-05-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0028_alter_well_active_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='north_direction',
            field=models.CharField(blank=True, choices=[('GRID', 'Картографический'), ('TRUE', 'Географический'), ('MAGN', 'Магнитный')], max_length=4, null=True, verbose_name='Направление на север'),
        ),
    ]
