# Generated by Django 4.0.3 on 2023-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0029_alter_well_north_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='status_drilling',
            field=models.CharField(blank=True, choices=[('ACTV', 'Активная стадия'), ('NOACT', 'Неактивная стадия')], max_length=5, null=True, verbose_name='Статус бурения'),
        ),
        migrations.AlterField(
            model_name='well',
            name='status',
            field=models.CharField(blank=True, choices=[('PLAN', 'Планируется'), ('NOTA', 'В бурении'), ('STOP', 'Приостановлена'), ('FINI', 'Добурена')], max_length=4, null=True, verbose_name='Статус состояния скважины'),
        ),
    ]
