# Generated by Django 4.0.3 on 2023-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0030_well_status_drilling_alter_well_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='mail_Cc',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Список рассылки Копия(mail)'),
        ),
        migrations.AddField(
            model_name='well',
            name='mail_To',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Список рассылки Кому(mail)'),
        ),
    ]
