# Generated by Django 4.0.3 on 2023-06-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0031_well_mail_cc_well_mail_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='comment',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='well',
            name='mail_Cc',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Список рассылки почта "Копия"'),
        ),
        migrations.AlterField(
            model_name='well',
            name='mail_To',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Список рассылки почта "Кому"'),
        ),
    ]
