# Generated by Django 4.0.3 on 2023-07-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0033_alter_section_target_depth_alter_well_ex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(choices=[('SMTL', 'Самотлорнефтегаз'), ('SKNG', 'Севкомнефтегаз'), ('UVAT', 'Уватнефтегаз'), ('SBNG', 'Сибнефтегаз'), ('UDMR', 'Удмуртнефть'), ('TUNG', 'ТЮНГ'), ('UGNG', 'Юганскнефтегаз'), ('SLAV', 'Славнефть'), ('HRNG', 'Харампурнефтегаз'), ('RNHA', 'РНША'), ('VOIL', 'Восток Ойл'), ('PRNG', 'Пурнефтегаз'), ('VCNG', 'ВЧНГ')], max_length=4, unique=True, verbose_name='Заказчик'),
        ),
    ]
