# Generated by Django 4.0.3 on 2023-07-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0036_alter_client_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='EX',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота X (прямоугольные координаты), м'),
        ),
        migrations.AlterField(
            model_name='well',
            name='NY',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта Y (прямоугольные координаты), м'),
        ),
        migrations.AlterField(
            model_name='well',
            name='latitude',
            field=models.TextField(blank=True, null=True, verbose_name='Широта географическая'),
        ),
        migrations.AlterField(
            model_name='well',
            name='longtitude',
            field=models.TextField(blank=True, null=True, verbose_name='Долгота географическая'),
        ),
    ]
