# Generated by Django 4.0.3 on 2023-08-03 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0037_alter_well_ex_alter_well_ny_alter_well_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время создания')),
                ('well', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='Field.well', verbose_name='Сводка')),
            ],
            options={
                'verbose_name': 'Сводка',
                'verbose_name_plural': 'Сводка',
            },
        ),
    ]
