# Generated by Django 4.0.3 on 2023-08-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0039_well_igirgi_drilling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='well',
            name='igirgi_drilling',
        ),
    ]
