# Generated by Django 4.0.3 on 2023-08-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0040_remove_well_igirgi_drilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellbore',
            name='igirgi_drilling',
            field=models.BooleanField(blank=True, default=False, verbose_name='Бурение по траектории ИГиРГИ'),
        ),
    ]
