# Generated by Django 4.0.3 on 2023-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_dynamic_depth', models.CharField(max_length=10, null=True, verbose_name='Сырые динамические глубина')),
                ('raw_dynamic_corner', models.CharField(max_length=10, null=True, verbose_name='Сырые динамические угол')),
                ('nnb_static_depth', models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ глубина')),
                ('nnb_static_corner', models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ угол')),
                ('nnb_static_azimut', models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ азимут')),
                ('nnb_static_list_number', models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ номер эксель')),
                ('nnb_dynamic_depth', models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ глубина')),
                ('nnb_dynamic_corner', models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ угол')),
                ('nnb_dynamic_azimut', models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ азимут')),
                ('nnb_dynamic_list_number', models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ номер эксель')),
                ('igirgi_static_depth', models.CharField(max_length=10, null=True, verbose_name='Статические ИГиРГИ глубина')),
                ('igirgi_static_corner', models.CharField(max_length=10, null=True, verbose_name='Статические ИГиРГИ угол')),
                ('igirgi_static_azimut', models.CharField(max_length=10, null=True, verbose_name='Статические ИГиРГИ азимут')),
            ],
            options={
                'verbose_name': 'Индексы для формы с отчетами',
            },
        ),
    ]
