# Generated by Django 4.0.3 on 2023-01-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportindex',
            table='report_index',
        ),
    ]
