# Generated by Django 4.0.3 on 2023-01-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_reportindex_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportindex',
            name='nnb_dynamic_list_number',
        ),
        migrations.RemoveField(
            model_name='reportindex',
            name='nnb_static_list_number',
        ),
        migrations.AddField(
            model_name='reportindex',
            name='igirgi_list_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Статические ИГиРГИ лист эксель'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='nnb_dynamic_list_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Динамические от ННБ лист эксель'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='nnb_static_list_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Статические от ННБ лист эксель'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='plan_azimut',
            field=models.CharField(max_length=10, null=True, verbose_name='Плановая траектория азимут'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='plan_corner',
            field=models.CharField(max_length=10, null=True, verbose_name='Плановая траектория угол'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='plan_depth',
            field=models.CharField(max_length=10, null=True, verbose_name='Плановая траектория глубина'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='plan_list_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Плановая траектория лист эксель'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='raw_dynamic_list_name',
            field=models.CharField(max_length=10, null=True, verbose_name='Сырые динамические лист эксель'),
        ),
    ]
