# Generated by Django 4.0.3 on 2023-01-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0015_telesystemindex_depth'),
        ('report', '0003_remove_reportindex_nnb_dynamic_list_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportindex',
            name='run',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run'),
        ),
    ]
