# Generated by Django 4.0.3 on 2023-02-11 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0015_telesystemindex_depth'),
        ('report', '0005_reportindex_nnb_dynamic_read_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportindex',
            options={'verbose_name': 'Индексы для формы'},
        ),
        migrations.AddField(
            model_name='reportindex',
            name='raw_dynamic_corner_excel',
            field=models.CharField(max_length=10, null=True, verbose_name='Сырые динамические угол excel'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='raw_dynamic_depth_excel',
            field=models.CharField(max_length=10, null=True, verbose_name='Сырые динамические глубина excel'),
        ),
        migrations.CreateModel(
            name='StaticNNBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(verbose_name='угол')),
                ('azimut', models.FloatField(verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run')),
            ],
            options={
                'verbose_name': 'Статические замеры ННБ',
                'db_table': 'static_NNB_data',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(verbose_name='угол')),
                ('azimut', models.FloatField(verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run')),
            ],
            options={
                'verbose_name': 'Замеры плановой траектории',
                'db_table': 'plan_data',
            },
        ),
        migrations.CreateModel(
            name='IgirgiStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run')),
            ],
            options={
                'verbose_name': 'Статические замеры ИГИРГИ',
                'db_table': 'static_igirgi_data',
            },
        ),
        migrations.CreateModel(
            name='IgirgiDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run')),
            ],
            options={
                'verbose_name': 'Статические замеры ИГИРГИ',
                'db_table': 'dynamic_igirgi_data',
            },
        ),
        migrations.CreateModel(
            name='DynamicNNBData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(verbose_name='угол')),
                ('azimut', models.FloatField(verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run')),
            ],
            options={
                'verbose_name': 'Динамические замеры ННБ',
                'db_table': 'dynamic_NNB_data',
            },
        ),
    ]
