# Generated by Django 4.0.3 on 2023-02-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_reportindex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportindex',
            name='igirgi_str',
            field=models.IntegerField(null=True, verbose_name='Считываем данные с этой строки'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='plan_str',
            field=models.IntegerField(null=True, verbose_name='Считываем данные с этой строки'),
        ),
        migrations.AddField(
            model_name='reportindex',
            name='raw_str',
            field=models.IntegerField(null=True, verbose_name='Считываем данные с этой строки'),
        ),
        migrations.AlterField(
            model_name='reportindex',
            name='nnb_dynamic_read',
            field=models.IntegerField(null=True, verbose_name='Динамические от ННБ метры с которых счтываем'),
        ),
        migrations.AlterField(
            model_name='reportindex',
            name='nnb_static_read',
            field=models.IntegerField(null=True, verbose_name='Статические от ННБ метры с которых счтываем'),
        ),
    ]
