# Generated by Django 4.0.3 on 2023-02-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_reportindex_igirgi_str_reportindex_plan_str_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igirgidynamic',
            options={'verbose_name': 'Динамические замеры ИГИРГИ'},
        ),
    ]
