# Generated by Django 4.0.3 on 2023-02-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0016_alter_data_run_alter_run_wellbore_and_more'),
        ('report', '0008_alter_igirgidynamic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicnnbdata',
            options={'verbose_name': 'Динамический замер ННБ', 'verbose_name_plural': 'Динамические замеры ННБ'},
        ),
        migrations.AlterModelOptions(
            name='igirgidynamic',
            options={'verbose_name': 'Динамический замер ИГИРГИ', 'verbose_name_plural': 'Динамические замеры ИГИРГИ'},
        ),
        migrations.AlterModelOptions(
            name='igirgistatic',
            options={'verbose_name': 'Статический замер ИГИРГИ', 'verbose_name_plural': 'Статические замеры ИГИРГИ'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Замер плановой траектории', 'verbose_name_plural': 'Замеры плановой траектории'},
        ),
        migrations.AlterModelOptions(
            name='reportindex',
            options={'verbose_name': 'Индекс для формы', 'verbose_name_plural': 'Индексы для формы'},
        ),
        migrations.AlterModelOptions(
            name='staticnnbdata',
            options={'verbose_name': 'Статический замер ННБ', 'verbose_name_plural': 'Статические замеры ННБ'},
        ),
        migrations.AlterField(
            model_name='reportindex',
            name='igirgi_str',
            field=models.IntegerField(null=True, verbose_name='Считываем данные статика ИГиРГИ с этой строки'),
        ),
        migrations.AlterField(
            model_name='reportindex',
            name='nnb_dynamic_read',
            field=models.IntegerField(null=True, verbose_name='Считываем динамические данные  от ННБ с этой строки'),
        ),
        migrations.AlterField(
            model_name='reportindex',
            name='nnb_static_read',
            field=models.IntegerField(null=True, verbose_name='Считываем статические данные от ННБ с этой строки'),
        ),
        migrations.AlterField(
            model_name='reportindex',
            name='plan_str',
            field=models.IntegerField(null=True, verbose_name='Считываем данные плана с этой строки'),
        ),
        migrations.AlterField(
            model_name='reportindex',
            name='raw_str',
            field=models.IntegerField(null=True, verbose_name='Считываем сырые данные с этой строки'),
        ),
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(verbose_name='угол')),
                ('azimut', models.FloatField(verbose_name='азимут')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run')),
            ],
            options={
                'verbose_name': 'Сырой замер',
                'verbose_name_plural': 'ДСырые замер',
                'db_table': 'raw_data',
            },
        ),
    ]
