# Generated by Django 4.0.3 on 2023-02-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_alter_dynamicnnbdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raw',
            options={'verbose_name': 'Сырой замер', 'verbose_name_plural': 'Сырые замер'},
        ),
        migrations.AlterField(
            model_name='dynamicnnbdata',
            name='azimut',
            field=models.FloatField(null=True, verbose_name='азимут'),
        ),
        migrations.AlterField(
            model_name='dynamicnnbdata',
            name='corner',
            field=models.FloatField(null=True, verbose_name='угол'),
        ),
        migrations.AlterField(
            model_name='igirgidynamic',
            name='corner',
            field=models.FloatField(null=True, verbose_name='угол'),
        ),
        migrations.AlterField(
            model_name='igirgistatic',
            name='corner',
            field=models.FloatField(null=True, verbose_name='угол'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='azimut',
            field=models.FloatField(null=True, verbose_name='азимут'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='corner',
            field=models.FloatField(null=True, verbose_name='угол'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='azimut',
            field=models.FloatField(null=True, verbose_name='азимут'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='corner',
            field=models.FloatField(null=True, verbose_name='угол'),
        ),
        migrations.AlterField(
            model_name='staticnnbdata',
            name='azimut',
            field=models.FloatField(null=True, verbose_name='азимут'),
        ),
        migrations.AlterField(
            model_name='staticnnbdata',
            name='corner',
            field=models.FloatField(null=True, verbose_name='угол'),
        ),
    ]
