# Generated by Django 4.0.3 on 2023-02-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_raw_options_alter_dynamicnnbdata_azimut_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicnnbdata',
            options={'ordering': ['depth'], 'verbose_name': 'Динамический замер ННБ', 'verbose_name_plural': 'Динамические замеры ННБ'},
        ),
        migrations.AlterModelOptions(
            name='igirgidynamic',
            options={'ordering': ['depth'], 'verbose_name': 'Динамический замер ИГИРГИ', 'verbose_name_plural': 'Динамические замеры ИГИРГИ'},
        ),
        migrations.AlterModelOptions(
            name='igirgistatic',
            options={'ordering': ['depth'], 'verbose_name': 'Статический замер ИГИРГИ', 'verbose_name_plural': 'Статические замеры ИГИРГИ'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['depth'], 'verbose_name': 'Замер плановой траектории', 'verbose_name_plural': 'Замеры плановой траектории'},
        ),
        migrations.AlterModelOptions(
            name='raw',
            options={'ordering': ['depth'], 'verbose_name': 'Сырой замер', 'verbose_name_plural': 'Сырые замер'},
        ),
        migrations.AlterModelOptions(
            name='staticnnbdata',
            options={'ordering': ['depth'], 'verbose_name': 'Статический замер ННБ', 'verbose_name_plural': 'Статические замеры ННБ'},
        ),
    ]
