# Generated by Django 4.0.3 on 2023-03-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0004_alter_field_field_name_alter_well_status'),
        ('report', '0012_alter_dynamicnnbdata_table_alter_igirgidynamic_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicnnbdata',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.AlterField(
            model_name='igirgidynamic',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.AlterField(
            model_name='igirgistatic',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.AlterField(
            model_name='raw',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.AlterField(
            model_name='reportindex',
            name='run',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.AlterField(
            model_name='staticnnbdata',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
    ]
