# Generated by Django 4.0.3 on 2023-03-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0004_alter_field_field_name_alter_well_status'),
        ('report', '0013_alter_dynamicnnbdata_run_alter_igirgidynamic_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportindex',
            name='run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
    ]
