# Generated by Django 4.0.3 on 2023-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_alter_reportindex_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_version',
            field=models.CharField(max_length=20, null=True, verbose_name='версия плана'),
        ),
    ]
