# Generated by Django 4.0.3 on 2023-08-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0041_wellbore_igirgi_drilling'),
        ('report', '0015_plan_plan_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='igirgistatic',
            name='comment',
            field=models.TextField(null=True, verbose_name='комментарий'),
        ),
    ]
