# Generated by Django 4.0.3 on 2023-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_plan_plan_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticnnbdata',
            name='comment',
            field=models.TextField(null=True, verbose_name='комментарий'),
        ),
    ]
