# Generated by Django 4.0.3 on 2023-08-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0041_wellbore_igirgi_drilling'),
        ('report', '0016_staticnnbdata_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(verbose_name='глубина')),
                ('corner', models.FloatField(null=True, verbose_name='угол')),
                ('azimut', models.FloatField(null=True, verbose_name='азимут')),
                ('comment', models.TextField(null=True, verbose_name='комментарий')),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run')),
            ],
            options={
                'verbose_name': 'Замер интерполированной плановой траектории',
                'verbose_name_plural': 'Замеры интерполированной плановой траектории',
                'db_table': 'meas_intr_plan',
                'ordering': ['depth'],
            },
        ),
    ]
