# Generated by Django 4.0.3 on 2023-08-28 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0041_wellbore_igirgi_drilling'),
        ('report', '0016_igirgistatic_comment_staticnnbdata_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X (Запад/Восток)')),
                ('hor_x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X (Запад/Восток)')),
                ('hor_x_del', models.IntegerField(null=True, verbose_name='Шаг по X (Запад/Восток)')),
                ('hor_y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y (Юг/Север)')),
                ('hor_y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y (Юг/Север)')),
                ('hor_y_del', models.IntegerField(null=True, verbose_name='Шаг по Y (Юг/Север)')),
                ('ver_x_min', models.IntegerField(null=True, verbose_name='Минимальное значение по X (Вертикальная секция)')),
                ('ver_x_max', models.IntegerField(null=True, verbose_name='Максимальное значение по X (Вертикальная секция)')),
                ('ver_x_del', models.IntegerField(null=True, verbose_name='Шаг по X (Вертикальная секция)')),
                ('ver_y_min', models.IntegerField(null=True, verbose_name='Минимальное значение по Y (Абсолютная отметка)')),
                ('ver_y_max', models.IntegerField(null=True, verbose_name='Максимальное значение по Y (Абсолютная отметка)')),
                ('ver_y_del', models.IntegerField(null=True, verbose_name='Шаг по Y (Абсолютная отметка)')),
                ('wellbore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_params', to='Field.wellbore', verbose_name='Параметры преокции')),
            ],
            options={
                'verbose_name': 'Параметры для построения проекции',
                'verbose_name_plural': 'Параметры для построения проекции',
                'db_table': 'report_proj_graph',
            },
        ),
    ]
