# Generated by Django 4.0.3 on 2023-08-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_interpplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='igirgistatic',
            name='comment',
            field=models.TextField(null=True, verbose_name='комментарий'),
        ),
    ]
