# Generated by Django 4.0.3 on 2023-08-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0042_wellbore_current_depth'),
        ('report', '0017_alter_reportindex_table_projectionparam_interpplan'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportindex',
            table='report_trajectory_index',
        ),
    ]
