# Generated by Django 4.0.3 on 2023-08-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_igirgistatic_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpplan',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='staticnnbdata',
            name='comment',
        ),
    ]
