# Generated by Django 4.0.3 on 2023-08-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_alter_reportindex_table_interpplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportindex',
            name='nnb_static_exclude_proj',
            field=models.BooleanField(default=False, verbose_name='Флаг на исключение проекции'),
        ),
    ]
