# Generated by Django 4.0.3 on 2023-08-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_staticnnbdata_comment_alter_reportindex_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectionparam',
            name='hor_x_del',
            field=models.IntegerField(null=True, verbose_name='Шаг по X (Запад/Восток)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='hor_x_max',
            field=models.IntegerField(null=True, verbose_name='Максимальное значение по X (Запад/Восток)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='hor_x_min',
            field=models.IntegerField(null=True, verbose_name='Минимальное значение по X (Запад/Восток)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='hor_y_del',
            field=models.IntegerField(null=True, verbose_name='Шаг по Y (Юг/Север)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='hor_y_max',
            field=models.IntegerField(null=True, verbose_name='Максимальное значение по Y (Юг/Север)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='hor_y_min',
            field=models.IntegerField(null=True, verbose_name='Минимальное значение по Y (Юг/Север)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='ver_x_del',
            field=models.IntegerField(null=True, verbose_name='Шаг по X (Вертикальная секция)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='ver_x_max',
            field=models.IntegerField(null=True, verbose_name='Максимальное значение по X (Вертикальная секция)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='ver_x_min',
            field=models.IntegerField(null=True, verbose_name='Минимальное значение по X (Вертикальная секция)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='ver_y_del',
            field=models.IntegerField(null=True, verbose_name='Шаг по Y (Абсолютная отметка)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='ver_y_max',
            field=models.IntegerField(null=True, verbose_name='Максимальное значение по Y (Абсолютная отметка)'),
        ),
        migrations.AlterField(
            model_name='projectionparam',
            name='ver_y_min',
            field=models.IntegerField(null=True, verbose_name='Минимальное значение по Y (Абсолютная отметка)'),
        ),
    ]
