# Generated by Django 4.0.5 on 2022-08-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.TextField(max_length=50, verbose_name='Сервисная компания')),
                ('device_title', models.TextField(max_length=50, verbose_name='Название прибора')),
                ('CX', models.TextField(max_length=50, verbose_name='CX')),
                ('CY', models.TextField(max_length=50, verbose_name='CY')),
                ('CZ', models.TextField(max_length=50, verbose_name='CZ')),
                ('BX', models.TextField(max_length=50, verbose_name='BX')),
                ('BY', models.TextField(max_length=50, verbose_name='BY')),
                ('BZ', models.TextField(max_length=50, verbose_name='BZ')),
            ],
        ),
    ]
