# Generated by Django 4.0.3 on 2022-08-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='файл')),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название скважины')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
            },
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Телесистема', 'verbose_name_plural': 'Телесистемы'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='company_title',
        ),
        migrations.AlterField(
            model_name='device',
            name='BX',
            field=models.CharField(max_length=50, verbose_name='BX'),
        ),
        migrations.AlterField(
            model_name='device',
            name='BY',
            field=models.CharField(max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='device',
            name='BZ',
            field=models.CharField(max_length=50, verbose_name='BZ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='CX',
            field=models.CharField(max_length=50, verbose_name='GX'),
        ),
        migrations.AlterField(
            model_name='device',
            name='CY',
            field=models.CharField(max_length=50, verbose_name='GY'),
        ),
        migrations.AlterField(
            model_name='device',
            name='CZ',
            field=models.CharField(max_length=50, verbose_name='GZ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_title',
            field=models.CharField(max_length=100, verbose_name='Название телесистемы'),
        ),
        migrations.CreateModel(
            name='WellBore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название ствола')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.well')),
            ],
            options={
                'verbose_name': 'Ствол',
                'verbose_name_plural': 'Стволы',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название рейса')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.wellbore')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.CharField(max_length=50, verbose_name='Глубина')),
                ('CX', models.CharField(max_length=50, verbose_name='GX')),
                ('CY', models.CharField(max_length=50, verbose_name='GY')),
                ('CZ', models.CharField(max_length=50, verbose_name='GZ')),
                ('BX', models.CharField(max_length=50, verbose_name='BX')),
                ('BY', models.CharField(max_length=50, verbose_name='BY')),
                ('BZ', models.CharField(max_length=50, verbose_name='BZ')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
    ]
