# Generated by Django 4.0.3 on 2022-08-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0002_request_well_alter_device_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='title',
            new_name='run_title',
        ),
        migrations.RenameField(
            model_name='well',
            old_name='title',
            new_name='well_title',
        ),
        migrations.RenameField(
            model_name='wellbore',
            old_name='title',
            new_name='wellbore_title',
        ),
    ]
