# Generated by Django 4.0.3 on 2022-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0003_rename_title_run_run_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='device',
            field=models.CharField(default=1, max_length=100, verbose_name='Телесистема'),
            preserve_default=False,
        ),
    ]
