# Generated by Django 4.0.3 on 2022-08-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0004_run_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='well',
            new_name='wellbore',
        ),
    ]
