# Generated by Django 4.0.3 on 2022-08-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0005_rename_well_run_wellbore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='wellbore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ствол', to='excel_parcer.wellbore'),
        ),
    ]
