# Generated by Django 4.0.3 on 2022-08-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0008_data_in_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='device',
        ),
    ]
