# Generated by Django 4.0.3 on 2023-01-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0010_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelesystemIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GX', models.SmallIntegerField(max_length=10, verbose_name='GX')),
                ('GY', models.SmallIntegerField(max_length=10, verbose_name='GY')),
                ('GZ', models.SmallIntegerField(max_length=10, verbose_name='GZ')),
                ('BX', models.SmallIntegerField(max_length=10, verbose_name='BX')),
                ('BY', models.SmallIntegerField(max_length=10, verbose_name='BY')),
                ('BZ', models.SmallIntegerField(max_length=10, verbose_name='BZ')),
                ('units', models.CharField(max_length=10, verbose_name='BZ')),
                ('string_index', models.SmallIntegerField(max_length=10, verbose_name='BZ')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run')),
            ],
        ),
    ]
