# Generated by Django 4.0.3 on 2023-01-19 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0011_telesystemindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesystemindex',
            options={'verbose_name': 'Индесы телесистемы', 'verbose_name_plural': 'Индесы телесистемы'},
        ),
        migrations.AddField(
            model_name='telesystemindex',
            name='device_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.device'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='BX',
            field=models.SmallIntegerField(verbose_name='BX'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='BY',
            field=models.SmallIntegerField(verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='BZ',
            field=models.SmallIntegerField(verbose_name='BZ'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='GX',
            field=models.SmallIntegerField(verbose_name='GX'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='GY',
            field=models.SmallIntegerField(verbose_name='GY'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='GZ',
            field=models.SmallIntegerField(verbose_name='GZ'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='run_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='string_index',
            field=models.SmallIntegerField(verbose_name='Импорт со строки'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='units',
            field=models.SmallIntegerField(verbose_name='Строка единиц измерения'),
        ),
    ]
