# Generated by Django 4.0.3 on 2023-01-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0012_alter_telesystemindex_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telesystemindex',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='telesystemindex',
            old_name='run_id',
            new_name='run',
        ),
    ]
