# Generated by Django 4.0.3 on 2023-01-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0013_rename_device_id_telesystemindex_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telesystemindex',
            name='BX',
            field=models.CharField(max_length=4, verbose_name='BX'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='BY',
            field=models.CharField(max_length=4, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='BZ',
            field=models.CharField(max_length=4, verbose_name='BZ'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='GX',
            field=models.CharField(max_length=4, verbose_name='GX'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='GY',
            field=models.CharField(max_length=4, verbose_name='GY'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='GZ',
            field=models.CharField(max_length=4, verbose_name='GZ'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='string_index',
            field=models.CharField(max_length=4, verbose_name='Импорт со строки'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='units',
            field=models.CharField(max_length=4, verbose_name='Строка единиц измерения'),
        ),
    ]
