# Generated by Django 4.0.3 on 2023-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0014_alter_telesystemindex_bx_alter_telesystemindex_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telesystemindex',
            name='depth',
            field=models.CharField(default=3, max_length=4, verbose_name='Глубина'),
            preserve_default=False,
        ),
    ]
