# Generated by Django 4.0.3 on 2023-02-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0015_telesystemindex_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='wellbore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.wellbore'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='run',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.run'),
        ),
        migrations.AlterField(
            model_name='wellbore',
            name='well',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excel_parcer.well'),
        ),
    ]
