# Generated by Django 4.0.3 on 2023-03-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0018_rename_dip_convergence_well_grid_convergence'),
        ('excel_parcer', '0016_alter_data_run_alter_run_wellbore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.AlterField(
            model_name='telesystemindex',
            name='run',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
