# Generated by Django 4.0.3 on 2023-03-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0017_alter_data_run_alter_telesystemindex_run_delete_run'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RemoveField(
            model_name='wellbore',
            name='well',
        ),
        migrations.DeleteModel(
            name='Well',
        ),
        migrations.DeleteModel(
            name='WellBore',
        ),
    ]
