# Generated by Django 4.0.3 on 2023-03-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0018_rename_dip_convergence_well_grid_convergence'),
        ('excel_parcer', '0018_delete_request_remove_wellbore_well_delete_well_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BX',
            field=models.CharField(max_length=50, null=True, verbose_name='BX'),
        ),
        migrations.AlterField(
            model_name='data',
            name='BY',
            field=models.CharField(max_length=50, null=True, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='data',
            name='BZ',
            field=models.CharField(max_length=50, null=True, verbose_name='BZ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CX',
            field=models.CharField(max_length=50, null=True, verbose_name='GX'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CY',
            field=models.CharField(max_length=50, null=True, verbose_name='GY'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CZ',
            field=models.CharField(max_length=50, null=True, verbose_name='GZ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='in_statistics',
            field=models.BooleanField(null=True, verbose_name='Учитывать в статистике'),
        ),
        migrations.AlterField(
            model_name='data',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Field.run'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название телесистемы'),
        ),
    ]
