# Generated by Django 4.0.3 on 2023-03-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0019_alter_data_bx_alter_data_by_alter_data_bz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BX',
            field=models.FloatField(max_length=50, null=True, verbose_name='BX'),
        ),
        migrations.AlterField(
            model_name='data',
            name='BY',
            field=models.FloatField(max_length=50, null=True, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='data',
            name='BZ',
            field=models.FloatField(max_length=50, null=True, verbose_name='BZ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CX',
            field=models.FloatField(max_length=50, null=True, verbose_name='GX'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CY',
            field=models.FloatField(max_length=50, null=True, verbose_name='GY'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CZ',
            field=models.FloatField(max_length=50, null=True, verbose_name='GZ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='depth',
            field=models.FloatField(max_length=50, verbose_name='Глубина'),
        ),
    ]
