# Generated by Django 4.0.3 on 2023-06-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0020_alter_data_bx_alter_data_by_alter_data_bz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Btotal_corr',
            field=models.FloatField(default=0, verbose_name='Btotal_corr'),
        ),
        migrations.AddField(
            model_name='data',
            name='DIP_corr',
            field=models.FloatField(default=0, verbose_name='DIP_corr'),
        ),
        migrations.AlterField(
            model_name='data',
            name='BX',
            field=models.FloatField(max_length=10, null=True, verbose_name='BX'),
        ),
        migrations.AlterField(
            model_name='data',
            name='BY',
            field=models.FloatField(max_length=10, null=True, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='data',
            name='BZ',
            field=models.FloatField(max_length=10, null=True, verbose_name='BZ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CX',
            field=models.FloatField(max_length=10, null=True, verbose_name='GX'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CY',
            field=models.FloatField(max_length=10, null=True, verbose_name='GY'),
        ),
        migrations.AlterField(
            model_name='data',
            name='CZ',
            field=models.FloatField(max_length=10, null=True, verbose_name='GZ'),
        ),
        migrations.AlterField(
            model_name='data',
            name='depth',
            field=models.FloatField(max_length=10, verbose_name='Глубина'),
        ),
    ]
