# Generated by Django 4.0.3 on 2023-07-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0021_data_btotal_corr_data_dip_corr_alter_data_bx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Btotal_corr',
            field=models.FloatField(null=True, verbose_name='Btotal_corr'),
        ),
        migrations.AlterField(
            model_name='data',
            name='DIP_corr',
            field=models.FloatField(null=True, verbose_name='DIP_corr'),
        ),
    ]
