# Generated by Django 4.0.3 on 2023-08-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0022_alter_data_btotal_corr_alter_data_dip_corr'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='comment',
            field=models.TextField(blank='True', null=True, verbose_name='Комментарий'),
        ),
    ]
