# Generated by Django 4.0.3 on 2023-08-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_parcer', '0023_data_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='comment',
            field=models.TextField(blank='True', default='', null=True, verbose_name='Комментарий'),
        ),
    ]
