# Generated by Django 4.0.3 on 2023-08-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0041_wellbore_igirgi_drilling'),
        ('excel_parcer', '0024_alter_data_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelesystemIndex',
            new_name='AxesFileIndex',
        ),
    ]
